[versions]
kotlin = "2.2.0-RC" # Also change in buildSrc
botcommands = "3.0.0-beta.2_DEV"
jda = "5.5.1"
mockk = "1.13.16"
bytebuddy = "1.17.5"
logback-classic = "1.5.18"
kotlin-logging = "7.0.3"

[libraries]
botcommands = { module = "io.github.freya022:BotCommands", version.ref = "botcommands" }
jda = { module = "net.dv8tion:JDA", version.ref = "jda" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
bytebuddy = { module = "net.bytebuddy:byte-buddy", version.ref = "bytebuddy" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-classic" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }